# Generated by Django 5.1.4 on 2024-12-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_date_tbd',
            field=models.BooleanField(default=False),
        ),
    ]
