# Generated by Django 5.1.4 on 2024-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='last', max_length=255),
            preserve_default=False,
        ),
    ]
