# Generated by Django 5.1.4 on 2024-12-12 06:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_name_ticket_first_name_ticket_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
