# Generated by Django 5.1.4 on 2024-12-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code_base64',
        ),
    ]
